import{describe,expect,it}from'vitest';import type Phaser from'phaser';import{heroineDisplayHeight,playHeroinePose}from'./HeroinePose';

describe('heroine display scale',()=>{it('gives 4v4 a readable fitted-viewport silhouette without changing the master',()=>{expect(heroineDisplayHeight(4)).toBe(108);expect(heroineDisplayHeight(3)).toBe(122);expect(heroineDisplayHeight(1)).toBe(160)})});

describe('heroine pose sizing',()=>{it('keeps every source texture on the actor display height',()=>{const calls:{key?:string;width?:number;height?:number}={},data=new Map<string,unknown>([['heroine',true],['poseLocked',false],['heroHeight',96],['heroBaseY',-8]]),sprite={getData:(key:string)=>data.get(key),setData:(key:string,value:unknown)=>{data.set(key,value);return sprite},play:(key:string)=>{calls.key=key;return sprite},texture:{getSourceImage:()=>({width:846,height:1499})},setDisplaySize:(width:number,height:number)=>{calls.width=width;calls.height=height;return sprite},setY:()=>sprite}as unknown as Phaser.GameObjects.Sprite;playHeroinePose(sprite,'strike');expect(calls).toEqual({key:'heroine-strike',width:54,height:96})})});

describe('heroine down sizing',()=>{it('keeps the horizontal death drawing grounded to the standing pivot',()=>{const calls:{width?:number;height?:number;y?:number}={},data=new Map<string,unknown>([['heroine',true],['poseLocked',false],['heroHeight',100],['heroBaseY',-8]]),sprite={getData:(key:string)=>data.get(key),setData:(key:string,value:unknown)=>{data.set(key,value);return sprite},play:()=>sprite,texture:{getSourceImage:()=>({width:600,height:330})},setDisplaySize:(width:number,height:number)=>{calls.width=width;calls.height=height;return sprite},setY:(y:number)=>{calls.y=y;return sprite}}as unknown as Phaser.GameObjects.Sprite;playHeroinePose(sprite,'down');expect(calls).toEqual({width:95,height:52,y:16})})});

describe('trial character runtime poses',()=>{it('does not rotate dedicated down art',()=>{const calls:{angle?:number;tint?:number;width?:number;height?:number}={},data=new Map<string,unknown>([['heroine',true],['poseLocked',true],['heroHeight',100],['heroBaseY',-8]]),sprite={getData:(key:string)=>data.get(key),setData:(key:string,value:unknown)=>{data.set(key,value);return sprite},play:()=>sprite,texture:{getSourceImage:()=>({width:600,height:330})},setDisplaySize:(width:number,height:number)=>{calls.width=width;calls.height=height;return sprite},setY:()=>sprite,setAngle:(angle:number)=>{calls.angle=angle;return sprite},setTint:(tint:number)=>{calls.tint=tint;return sprite}}as unknown as Phaser.GameObjects.Sprite;playHeroinePose(sprite,'down');expect(calls).toMatchObject({width:164,height:90,angle:0,tint:0xb9aab4})})});

describe('pose-locked runtime trial',()=>{it('keeps the approved master texture while applying shared display height',()=>{const calls:{played?:string;width?:number;height?:number}={},data=new Map<string,unknown>([['heroine',true],['poseLocked',true],['heroHeight',96],['heroBaseY',-8]]),sprite={getData:(key:string)=>data.get(key),setData:(key:string,value:unknown)=>{data.set(key,value);return sprite},play:(key:string)=>{calls.played=key;return sprite},texture:{getSourceImage:()=>({width:1407,height:970})},setDisplaySize:(width:number,height:number)=>{calls.width=width;calls.height=height;return sprite},setY:()=>sprite,setAngle:()=>sprite,setTint:()=>sprite}as unknown as Phaser.GameObjects.Sprite;playHeroinePose(sprite,'strike');expect(calls).toEqual({width:139,height:96})})});
