"""Remove a bright baked checkerboard from a generated character candidate.

This is intentionally conservative: only bright, near-neutral pixels connected
to the image edge are classified as background, so enclosed ivory costume
areas remain opaque. The output is cropped to the alpha bounds with padding.
"""

from __future__ import annotations

import argparse
from collections import deque
from math import sqrt
from pathlib import Path

from PIL import Image


def clean(source: Path, output: Path, padding: int = 32, key_color: tuple[int, int, int] | None = None, tolerance: int = 54) -> Image.Image:
    image = Image.open(source).convert("RGBA")
    width, height = image.size
    pixels = image.load()
    background = bytearray(width * height)
    queue: deque[tuple[int, int]] = deque()

    def is_background_candidate(x: int, y: int) -> bool:
        red, green, blue, _ = pixels[x, y]
        if key_color is not None:
            if key_color[1] > key_color[0] + 100 and key_color[1] > key_color[2] + 100:
                return green >= 105 and green - max(red, blue) >= 42
            return sum((value - key) ** 2 for value, key in zip((red, green, blue), key_color)) <= tolerance ** 2
        return min(red, green, blue) >= 232 and max(red, green, blue) - min(red, green, blue) <= 18

    for x in range(width):
        queue.append((x, 0))
        queue.append((x, height - 1))
    for y in range(height):
        queue.append((0, y))
        queue.append((width - 1, y))

    while queue:
        x, y = queue.popleft()
        index = y * width + x
        if background[index] or not is_background_candidate(x, y):
            continue
        background[index] = 1
        for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if 0 <= nx < width and 0 <= ny < height and not background[ny * width + nx]:
                queue.append((nx, ny))

    green_key = key_color is not None and key_color[1] > key_color[0] + 100 and key_color[1] > key_color[2] + 100
    if green_key:
        # Chroma backdrops generated by image models often contain broad
        # brightness gradients separated by non-key bands. Green is excluded
        # from this character palette, so remove every strongly green pixel,
        # not only the region reachable by an exact-color flood fill.
        for y in range(height):
            for x in range(width):
                red, green, blue, _ = pixels[x, y]
                if green >= 90 and green - max(red, blue) >= 34:
                    background[y * width + x] = 1

    for y in range(height):
        for x in range(width):
            red, green, blue, _ = pixels[x, y]
            if background[y * width + x]:
                pixels[x, y] = (red, green, blue, 0)
                continue
            if key_color is not None:
                adjacent_background = any(
                    0 <= nx < width and 0 <= ny < height and background[ny * width + nx]
                    for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1))
                )
                distance = sqrt(sum((value - key) ** 2 for value, key in zip((red, green, blue), key_color)))
                green_spill = green - max(red, blue)
                if adjacent_background and (distance < tolerance * 2.4 or (green_key and green_spill > 10)):
                    alpha = max(1, min(255, round((1 - green_spill / 255) * 255) if green_key else round((distance - tolerance) / (tolerance * 1.4) * 255)))
                    fraction = alpha / 255
                    cleaned = tuple(max(0, min(255, round((value - key * (1 - fraction)) / fraction))) for value, key in zip((red, green, blue), key_color))
                    pixels[x, y] = (*cleaned, alpha)
                    continue
            if key_color is None and min(red, green, blue) >= 190 and max(red, green, blue) - min(red, green, blue) <= 22:
                adjacent_background = any(
                    0 <= nx < width and 0 <= ny < height and background[ny * width + nx]
                    for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1))
                )
                if adjacent_background:
                    alpha = max(0, min(255, round((255 - min(red, green, blue)) / 65 * 255)))
                    pixels[x, y] = (red, green, blue, alpha)

    alpha = image.getchannel("A")
    bounds = alpha.getbbox()
    if bounds is None:
        raise RuntimeError("No foreground remained after background cleanup")
    left = max(0, bounds[0] - padding)
    top = max(0, bounds[1] - padding)
    right = min(width, bounds[2] + padding)
    bottom = min(height, bounds[3] + padding)
    result = image.crop((left, top, right, bottom))
    output.parent.mkdir(parents=True, exist_ok=True)
    result.save(output)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--key-color", help="RGB chroma key, for example 0,255,0")
    parser.add_argument("--tolerance", type=int, default=54)
    args = parser.parse_args()
    key_color = tuple(int(value) for value in args.key_color.split(",")) if args.key_color else None
    if key_color is not None and len(key_color) != 3:
        raise ValueError("--key-color requires R,G,B")
    result = clean(args.source, args.output, key_color=key_color, tolerance=args.tolerance)
    print(f"saved {args.output} {result.width}x{result.height} RGBA")


if __name__ == "__main__":
    main()
